name: mixhap
version: "1.0"
author: Haynes Heaton <whheaton@gmail.com>
about: phasing using Bernoulli mixture model clustering with EM
args:
    - variants:
        long: variants
        short: v
        takes_value: true
        required: true
        help: variant molecule support
    - ploidy: 
        long: ploidy
        short: p
        takes_value: true
        required: false
        help: ploidy
    - whitelist:
        long: barcode_whitelist
        short: b
        takes_value: true
        required: true
        help: barcode whitelist from 10x genomics longranger 
    - kmers:
        long: kmers
        takes_value: true
        required: true
        help: het_kmers.tsv file from het_snp_kmers
    - txg_mols:
        long: txg_mols
        takes_value: true
        multiple: true
        required: false
        help: 10x genomics linked read molecule binary file out of molecule_kmers program
    - longread_mols:
        long: longread_mols
        takes_value: true
        multiple: true
        required: false
        help: longread molecule binary file out of molecule_kmers program
    - longread_fqs:
        long: longread_fqs
        takes_value: true
        multiple: true
        required: true
        help: longread fastq files (must match order of longread_mols)
    - hic_mols:
        long: hic_mols
        takes_value: true
        multiple: true
        required: false
        help: hic molecule binary file out of molecule_kmers program
    - output:
        long: output
        takes_value: true
        required: true
        help: output_directory
    - crib:
        long: crib
        takes_value: true
        required: false
        help: cheat sheet ordering of kmers
