[package]
name = "mixhap"
version = "0.1.0"
authors = ["wheaton5 <whheaton@gmail.com>"]
edition = "2018"

[dependencies]
clap = {version = "~2.27.0", features = ["yaml"]}
hashbrown = "0.1"
fnv = "1.0.6"
rand = "0.7.0"
bit-vec = "0.6.1"
cpuprofiler = "*"
